### ISSUE TITLE
Allow to choose the default mode

### ISSUE THREAD

**Issue by suhr** [johtela/vscode-modaledit#1]
On VS Code start, modalEdit is in the normal mode by default. It would be very nice to be able to chose the insert mode as default.

**Comment by johtela** [comment]
This should be easy to implement. I'll add the feature to next release.

**Comment by johtela** [comment]
Added `startInNormalMode` setting to configuration. If you set it `false` in `settings.json` or in UI, the editor starts initially in insert mode.

![Capture](https://user-images.githubusercontent.com/1577435/72930243-3006d700-3d64-11ea-9556-c7adf4bc428c.PNG)

The feature is in version 1.2.0
